openapi: 3.0.3
info:
  title: Swagger Petstore - yanchiAPI 3.0
  description: |-
  termsOfService: http://swagger.io/terms/
  license:
    name: yangchi_API
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/
tags:
  - name: auth
    description: auth
    externalDocs:
      description: Find out more
  - name: user
    description: Operations about user
paths:
  auth/login:
    post:
      tags:
        - auth
      summary: 로그인
      description: 로그인
      operationId: 로그인
      requestBody:
        description: auth
        content:
          application/json:
            schema:
              $ref: "#/components/"
          application/xml:
            schema:
              $ref: "#/components/schemas/auth"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/auth"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
            application/xml:
              schema:
                $ref: "#/components/schemas/Pet"
        "400":
          description: Invalid input
        "500":
          description: Internal server error
      security:
        - petstore_auth:
            - write:pets
            - read:pets
  auth/signup:
    post:
      tags:
        - auth
      summary: 회원가입
      description: 회원가입
      operationId: 회원가입
      requestBody:
        description: auth
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
          application/xml:
            schema:
              $ref: "#/components/schemas/Pet"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Pet"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
            application/xml:
              schema:
                $ref: "#/components/schemas/Pet"
        "400":
          description: Invalid input
        "500":
          description: Internal server error
      security:
        - petstore_auth:
            - write:pets
            - read:pets